language: r
r:
  - release
  - devel

sudo: required

env: NOT_CRAN="true"

r_binary_packages:
  - testthat
  - knitr
  - rmarkdown

branches:
  only:
    - master
    - release
    - dev
    
notifications:
  email:
    on_success: change
    on_failure: change
    