language: r
dist: trusty
cache: packages
sudo: false

r:
  - release
  - devel

env: 
  - NOT_CRAN="true"
  - NOT_CRAN="false"
  
r_binary_packages:
  - knitr
  - rmarkdown

branches:
  only:
    - master
    - release
    - dev
    
notifications:
  email:
    on_success: change
    on_failure: change
    
after_success:
  - Rscript -e 'covr::codecov()'
    