language: r
cache: packages
sudo: false

r:
  - release
  - devel

env: 
  - NOT_CRAN="true"
  - NOT_CRAN="false"

branches:
  only:
    - master
    - release
    - dev
    
notifications:
  email:
    on_success: change
    on_failure: change
    